version: 2

builds:
  - id: tsgo
    dir: tsgo
    main: ./cmd/tsgo
    binary: tsgo
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm64
    flags:
      - -tags=noembed
    env:
      - CGO_ENABLED=0

  - id: tsgo-wasm
    dir: tsgo
    main: ./cmd/tsgo
    binary: tsgo
    goos:
      - js
    goarch:
      - wasm
    env:
      - CGO_ENABLED=0

archives:
  - formats: tar.gz
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - src: tsgo/built/local/*
        strip_parent: true

changelog:
  disable: true

release:
  header: |
    Daily automated build of TypeScript-Go from https://github.com/microsoft/typescript-go.

    Build date: {{ .Tag }}

    ## Contents

    These archives contain all files from the `built/local` directory, including the `tsgo` binary.
